# Configuration for Travis-CI

language: java

# For enabling the generation of the native executables
sudo: required

matrix:
  fast_finish: true
  include:

    - os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
          - xvfb
          - lib32z1
          - lib32ncurses5
      before_install:
      - "sh -e ./build-tools/scripts/travis-download-maven.sh"
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx2g\"" > $HOME/.mavenrc
      env: DISPLAY=:99.0

    - os: osx
      osx_image: xcode8
      before_install:
      - "sh -e ./build-tools/scripts/travis-download-maven.sh"
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx2g -Dmaven.test.skip=true -Dcheckstyle.skip=true\"" > $HOME/.mavenrc

install: true

script: "mvn -B -e -P!generateproduct clean install"

#after_failure: "sh -e ./build-tools/scripts/print-surefire-reports.sh"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.binaries

